theme: jekyll-theme-minimal
title: Julian Barrera Web
description: Bookmark this to keep an eye on the personal projects of Julian Barrera! Guarda esta pagina para mantenerte al tanto de mi informacion profesion y mis proyectos. Soy Julian Barrera, Desarrollador.
